### ISSUE TITLE
How does Freenode::Prototypes differ from core Subroutines::ProhibitSubroutinePrototypes?

### ISSUE THREAD

**Issue by petdance** [Grinnz/Perl-Critic-Freenode#12]
Similar to #11, I don't see any indication of when I should use Freenode::Prototypes instead of Subroutines::ProhibitSubroutinePrototypes.

http://search.cpan.org/~dbook/Perl-Critic-Freenode/lib/Perl/Critic/Policy/Freenode/Prototypes.pm

vs.

http://search.cpan.org/~thaljef/Perl-Critic-1.125/lib/Perl/Critic/Policy/Subroutines/ProhibitSubroutinePrototypes.pm

**Comment by Grinnz** [comment]
In this case, the Freenode policy is more permissive; the core policy prohibits all prototypes, while the Freenode policy allows them if they are empty, if they contain &, or if the `signatures` feature is enabled.

**Comment by petdance** [comment]
That distinction would be excellent to have in the docs.

**Comment by Grinnz** [comment]
Clarified in commit b6bdee2
