### ISSUE TITLE
Warn that future Perl core changes might affect your script

### ISSUE THREAD

**Issue by vytas-dauksa** [Grinnz/Perl-Critic-Freenode#16]
Not sure if this is in scope for Perl::Critic::Freenode namespace, but for a while I was thinking - how nice it would be to have a module that reports deprecated/removed things in future Perl's than the one you are using.

It's a pain to implement and this can be already achieved by running your library against newer Perl versions ( perhaps with the help of Perlbrew or etc. ). Though, this would be great CI/code review tool.

**Comment by Grinnz** [comment]
I considered this but "use warnings" tends to cover it in most cases, however you make a good point that this won't cover older versions of perl. I will consider adding policies for deprecated or experimental features. Thanks for the idea.

**Comment by Grinnz** [comment]
added policy in v0.011
