### ISSUE TITLE
%sorters list in DollarAB does not have 'pairwise'

### ISSUE THREAD

**Issue by jemmix** [Grinnz/Perl-Critic-Freenode#21]
Thank you for a very useful policy of DollarAB, it is very helpful, let us catch a couple potential bugs in our codebase.

There's a caveat though- we're using pairwise in our code, and DollarAB complains about it. pairwise is exported by List::MoreUtils and List::AllUtils — granted, there's another policy that discourages using List::MoreUtils but getting rid of that dependency is not feasible for us at this time.

Can you please either add pairwise to the list, or, better yet, make the policy extensible so that the users could redefine the 'list of sorters' to suit their needs?

Thanks!

**Comment by Grinnz** [comment]
Good idea, I'll see what I can do

**Comment by Grinnz** [comment]
Fixed in 0.014
