### ISSUE TITLE
strictures exporters

### ISSUE THREAD

**Issue by shadowcat-mst** [Grinnz/Perl-Critic-Freenode#4]
common::sense doesn't export a full set of warnings so doesn't count; I think sanity.pm does count but I dunno if it has enough revdeps to matter.

However the policy definitely needs to be configurable since I commonly end up with e.g.

    package MyApp::Class;
    
    use Import::Into;
    use Moo ();
    use MyApp::Utils ();
    
    sub import {
        MyApp::Utils->import::into(1);
        Moo->import::into(1);
    }

and a similar MyApp::Role - and obviously I'd then want the policy to accept those.

**Comment by Grinnz** [comment]
It doesn't look like sanity.pm exports a full set of warnings or strictures by default either, I'm just going to leave it out for now. I'll add a extra_importers configuration option.
